version: "3.3"
services:
    react-app:
        build:
          context: .
          dockerfile: Dockerfile.dev
        image: node:alpine
        ports: 
          - "3000:3000"
        volumes: 
          - /app/node_modules
          - .:/app

